### ISSUE TITLE
No ratings are appearing, no errors in console

### ISSUE THREAD

**Issue by lednerg** [Secreto31126/youtube-music-ratings#4]
In Chrome and in a completely fresh install of Edge, I am not seeing any stars and there are no error messages in the console. I made a new API key just in case the quota had been reached, but that didn't fix it. My Google Cloud dashboard does show that requests are being made with my API key, so the extension appears to be doing something. I'm guessing YouTube changed something recently such as a class name or an id of a div, which they love doing.

Windows 10 Pro
Chrome 123.0.6312.86 (Official Build) (64-bit)
Edge 123.0.2420.65 (Official build) (64-bit)

**Comment by Secreto31126** [comment]
Hi!

I'm actually surprised someone else uses this extension 😂.

Yeah, I did notice the stars disappeared (again), but didn't prioritize fixing it. Let me get right into it, and maybe in a few hours it will be up again. I will also consider adding an option to customize the query string to prevent future deprecation.

Thanks for using this tiny side project of mine :)

**Comment by lednerg** [comment]
Oh, no problem. I tinker around a lot with CSS stylesheets for YouTube and I'm very familiar with them changing the DOM out of the blue. People are so quick to blame the script authors when things no longer work, and I didn't want you getting bad reviews. Thanks for jumping right on this!

**Comment by Secreto31126** [comment]
I just sent a patch update to revision, it will be available as soon as Google allows it. I added two new advanced customizations to modify the CSS selectors the extension most depend on, so in case they decide to break it again it won't depend on me to get it fixed.

Let me know when you get the update if it's fixed on your side. Thanks for opening the issue!

**Comment by lednerg** [comment]
Looks like it's up and running.

Hey just so you know, there's a free API service which keeps track of YouTube views, likes, dislikes, and even gives a rating for videos out of 5. It's from the people who make the extension called Return YouTube Dislike. They've been maintaining a database of YouTube likes and dislikes ever since YouTube got rid of dislikes.

Anyway, they only have two rules: you have to make sure to credit them and each client can't go over 100 requests per minute or 10,000 per day. They don't use API keys, it's done on a per IP basis. I use it for a script that I run on YouTube sometimes and it's been very reliable, I just had to make sure to add a slight delay between requests or else it gives an error.

[https://www.returnyoutubedislike.com/docs/fetching](https://www.returnyoutubedislike.com/docs/fetching)

**Comment by Secreto31126** [comment]
Thanks for the tip!

Although I would prefer using an API that doesn't require exposing a key to the world like I'm doing, I'm not in a position to go through a whole project rewrite like this. I already got a lot of work trying to decipher the API I'm supposed to use for a university task :)

In the meanwhile, I will close this issue as complete, and return to it when I have the time to do a full read of the docs. 

Thanks!
